<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-04-08
 * Time: 23:42
 */

namespace app\common\controller;


use think\Controller;
use think\facade\Session;
use think\facade\Request;

/**
 * Class AdminBase
 * @package app\common\controller
 * 运营中心管理基础控制器
 */

class AdminBase extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if( !Session::has('admin_info') && Request::action() !== 'login')
        {
            $this->error("您还未登陆，请先登录", "/admin/index/login");
        }else if(Session::has('admin_info') && Request::action() == 'login') {
            $this->redirect("/admin/index/index");
        }
    }

}