<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019-04-08
 * Time: 23:42
 */

namespace app\common\controller;


use app\common\model\AccessLog;
use think\Controller;
use think\facade\Request;

/**
 * Class AdminBase
 * @package app\common\controller
 * API接口基础控制器
 */

class ApiBase extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 记录访问日志到数据库
        $data = [];
        $data["ip"] = Request::ip();
        $data["url"] = Request::url();
        $data["param"] = json_encode(Request::param());

        $log = new AccessLog();
        $log->save($data);

       //if(!isWxClient()){
       //     $this->redirect("/api/Api_Error/error");
      //  }
    }

}