<?php
/**
 * Created by PhpStorm.
 * User: Peter
 * Date: 2019/4/30
 * Time: 20:55
 */

namespace app\common\controller;


use think\Controller;
use think\facade\Request;
use think\facade\Session;


class AreaBase extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        if( !Session::has('area_info') && Request::action() !== 'login' && Request::action() !== 'selectarea')
        {
            $this->error("您还未登陆，请先登录", "/area/index/login");
        }else if(Session::has('area_info') && Request::action() == 'login') {
            $this->redirect("/area/index/index");
        }else if(!Session::has('areas') && Request::action() === 'selectarea'){
            $this->error("您还未登陆，请先登录", "/area/index/login");
        }
    }

}