<?php
/**
 * Created by PhpStorm.
 * User: Peter
 * Date: 2019/4/30
 * Time: 20:53
 */

namespace app\common\controller;


use think\Controller;
use think\facade\Request;
use think\facade\Session;

class StoreBase extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if( !Session::has('store_info') && Request::action() !== 'login' && Request::action() !== 'selectstore')
        {
            $this->error("您还未登陆，请先登录", "/store/index/login");
        }else if(Session::has('store_info') && Request::action() === 'login') {
            $this->redirect("/store/index");
        }else if(!Session::has('stores') && Request::action() === 'selectstore'){
            $this->error("您还未登陆，请先登录", "/store/index/login");
        }
    }

}